insert into album values (default, 'business as usual', 25, 1982), (default, 'cargo', 25, 1983), (default, 'movement', 26, 1981 ), (default, 'low-life', 26, 1985 ), (default, 'brotherhood', 26, 1986), (default, 'wilder mind', 27, 2009 ), (default, 'white women', 28, 2014), (default, 'empty sky', 29, 1969), (default, 'honky chateau', 29, 1972), (default, 'midnight marauders', 30, 1993)

insert into album values (default, 'born to run', 31, 1975), (default, 'born in the USA', 31, 1984), (default, 'representing the mambo', 32, 1990), (default, 'feats dont fail me now', 32, 1974), (default, 'at fillmore east', 33, 1970), (default, 'eat a peach', 33, 1972), (default, 'synchronicity', 34, 1983), (default, 'electric ladyland', 35, 1968), (default, 'in utero', 36, 1993), (default, 'smoke and fire', 37, 1970), (default, 'morrison hotel', 38, 1970), (default, 'texas flood', 39, 1983), (default, 'eliminator', 40, 1983)

insert into artist values (default, 'red hot chili peppers'), (default, 'steely dan'), (default, 'b.b. king'), (default, 'led zeppelin'), (default, 'ice cube'), (default, 'rainbow'), (default, 'iron butterfly'), (default, 'lynyrd skynyrd'), (default, 'chuck berry'), (default, 'greg allman'), (default, 'rolling stones'), (default, 'ozzie osbourne'), (default, 'black sabbath'), (default, 'guns and roses'), (default, 'nas'), (default, 'the carpenters')


insert into artist values (default, 'the clash'), (default, 'kc and the sunshine band'), (default, 'u2'), (default, 'sublime'), (default, 'bob marley'), (default, 'rush'), (default, 'traffic'), (default, 'tom petty and the heartbreakers'), (default, 'men at work'), (default, 'new order'), (default, 'munford and sons'), (default, 'chromeo'), (default, 'elton john'), (default, 'a tribe called quest'), (default, 'bruce springsteen'), (default, 'little feat'), (default, 'allman brothers')


insert into artist values (default, 'the police'), (default, 'jimmy hendrix'), (default, 'nirvana'), (default, 'lord sutch'), (default, 'the doors'), (default, 'stevie ray vaughan'), (default, 'zz top')

insert into song values (default, 'who can it be now', 25), (default, 'land down under', 25), (default, 'i will wait', 27), (default, 'the cave', 27), (default, 'jealous', 28), (default, 'sexy socialite', 28), (default, 'rocket man', 29), (default, 'tiny dancer', 29), (default, 'we got the jazz', 30), (default, 'solid wall of sound', 30), (default, 'space program', 30), (default, 'bustas lament', 30), (default, 'born to run', 31), (default, 'born in the usa', 31), (default, 'spanish moon', 32), (default, 'aint wastin time no more', 33), (default, 'blue sky', 33), (default, 'roxanne', 34), (default, 'message in a bottle', 34), (default, 'purple haze', 35), (default, 'crosstown traffic', 35), (default, 'come as you are', 36), (default, 'lithium', 36), (default, 'cause i love you', 37), (default, 'flashing lights', 37), (default, 'roadhouse blues', 38), (default, 'light my fire', 38), (default, 'texas flood', 39), (default, 'pride and joy', 39), (default, 'little wing', 39), (default, 'sharp dressed man', 40), (default, 'la grange', 40), (default, 'cheap sunglasses', 40), (default, 'tush', 40), (default, 'legs', 40)
